language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - libncurses-dev
    - make
jobs:
  allow_failures:
  - os: windows
os:
- linux
- osx
- windows
script:
- ./configure
- make -j4
- make check
